LOCAL_PATH := $(call my-dir)/src
include $(CLEAR_VARS)

LOCAL_MODULE := raknet
LOCAL_SRC_FILES := \
EmailSender.cpp \
VariadicSQLParser.cpp \
LocklessTypes.cpp \
DS_BytePool.cpp \
GridSectorizer.cpp \
LinuxStrings.cpp \
RakPeer.cpp \
NetworkIDManager.cpp \
FormatString.cpp \
SignaledEvent.cpp \
ConsoleServer.cpp \
EpochTimeToString.cpp \
VariableListDeltaTracker.cpp \
NatPunchthroughServer.cpp \
_FindFirst.cpp \
RakWString.cpp \
SecureHandshake.cpp \
Rackspace.cpp \
MessageFilter.cpp \
CloudServer.cpp \
WSAStartupSingleton.cpp \
SHA1.cpp \
NatTypeDetectionClient.cpp \
VariableDeltaSerializer.cpp \
NatTypeDetectionCommon.cpp \
SimpleMutex.cpp \
CCRakNetSlidingWindow.cpp \
Gets.cpp \
DataCompressor.cpp \
UDPForwarder.cpp \
PacketFileLogger.cpp \
SendToThread.cpp \
FileOperations.cpp \
RakString.cpp \
DynDNS.cpp \
PacketLogger.cpp \
PacketOutputWindowLogger.cpp \
StringTable.cpp \
ReliabilityLayer.cpp \
EncodeClassName.cpp \
DS_HuffmanEncodingTree.cpp \
RakNetTransport2.cpp \
UDPProxyServer.cpp \
CloudCommon.cpp \
StringCompressor.cpp \
CheckSum.cpp \
CloudClient.cpp \
GetTime.cpp \
DS_ByteQueue.cpp \
DS_Table.cpp \
TwoWayAuthentication.cpp \
SocketLayer.cpp \
TeamBalancer.cpp \
ConnectionGraph2.cpp \
NetworkIDObject.cpp \
UDPProxyCoordinator.cpp \
RakSleep.cpp \
RakNetStatistics.cpp \
PacketizedTCP.cpp \
FileList.cpp \
TCPInterface.cpp \
BitStream.cpp \
PluginInterface2.cpp \
RakNetSocket.cpp \
FullyConnectedMesh2.cpp \
RakNetTypes.cpp \
rdlmalloc.cpp \
Router2.cpp \
NatPunchthroughClient.cpp \
UDPProxyClient.cpp \
TelnetTransport.cpp \
PacketConsoleLogger.cpp \
Rand.cpp \
Getche.cpp \
gettimeofday.cpp \
TableSerializer.cpp \
ReplicaManager3.cpp \
FileListTransfer.cpp \
IncrementalReadInterface.cpp \
HTTPConnection.cpp \
CommandParserInterface.cpp \
RakThread.cpp \
ReadyEvent.cpp \
LogCommandParser.cpp \
CCRakNetUDT.cpp \
DirectoryDeltaTransfer.cpp \
NatTypeDetectionServer.cpp \
Itoa.cpp \
SuperFastHash.cpp \
ThreadsafePacketLogger.cpp \
RakMemoryOverride.cpp \
RakNetCommandParser.cpp \
RPC4Plugin.cpp 


include $(BUILD_STATIC_LIBRARY)
